config/routes.rb
Dionisio::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users do
    get "/logout" => "devise/sessions#destroy", :as => 'logout'
  end

  root :to => 'application#index'
  post '/email/create/' => 'lista_emails#create' , :as => 'create_email'

  get "/eventos/new" => "evento#new" , :as => "new_evento"
  post "/eventos/new" => "evento#create", :as => "create_evento"

end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :user

  validates :titulo , :local, :data_inicio, :presence => true
  validate :validar_promoter

  before_save :definir_data_fim
  
  def definir_data_fim
    if self.data_fim.nil?
      self.data_fim = self.data_inicio.at_midnight + 1.day
    end
  end

  def validar_promoter
    #self.user ||= User.find self.user_id
    errors.add(:user, :promoter) unless self.user.promoter?
  end

end

app/models/lista_email.rb
# -*- coding: utf-8 -*-
class ListaEmail < ActiveRecord::Base
  validates :email, :uniqueness => true, :presence => true
  validate :validar_email
  def validar_email
    errors.add(:email, 'o email não é válido') if self.email.match(/[A-Za-z0-9\._-]+@[A-Za-z]+\.[A-Za-z]+/).nil?
  end
end

app/models/user.rb
# -*- coding: utf-8 -*-
class User < ActiveRecord::Base
  has_many :eventos
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :nome, :data_nascimento, :tipo, :promoter?
  validates :nome , :presence => true
  validate :validar_idade

  def validar_idade
    errors.add(:data_nascimento, :menor) if Date.today - 18.years < self.data_nascimento.to_date
  end

  def admin?
    self.tipo == 2
  end

  def promoter?
    self.tipo >= 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
    @email = ListaEmail.new
  end

end

app/controllers/evento_controller.rb
class EventoController < ApplicationController
  def new
    @evento = Evento.new
  end

  def create
    @evento = Evento.new params[:evento]
    @evento.user = current_user
    if @evento.save
      redirect_to root_path
    else
      render :new
    end
  end

end

app/controllers/lista_emails_controller.rb
# -*- coding: utf-8 -*-
class ListaEmailsController < ApplicationController
  def create
    email = ListaEmail.new params[:lista_email]
    if email.save
      redirect_to root_path, :notice => 'O Email foi salvo com sucesso!'
    else
      redirect_to root_path, :alert => 'O Email não foi salvo!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_inicio
    (DateTime.now - 100.years).year
  end

  def data_fim
    (DateTime.now - 18.years).year
  end
end

app/helpers/evento_helper.rb
module EventoHelper
end

app/helpers/lista_emails_helper.rb
module ListaEmailsHelper
end

app/views/application/index.html.erb
<div class="texto">
  <h1>Em breve o maior site de divulgação de eventos do Rio de Janeiro!</h1>
</div>
<div class="email">
  <%= form_for @email, :url => create_email_path do |f|%>
    <%= f.label :email, 'Email:' %>
    <%= f.text_field :email %>
    <%= f.submit 'Enviar' %>
  <%end%>
</div>

app/views/evento/new.html.erb
<h3>Criar Evento</h3>
<%= form_for @evento, :url => create_evento_path do |f| %>

  <div><%= f.label :titulo %><br />
    <%= f.text_field :titulo %></div>

  <div><%= f.label :local %><br />
    <%= f.text_field :local %></div>

  <div><%= f.label :data_inicio %><br />
    <%= f.text_field :data_inicio %></div>

  <div><%= f.label :data_fim %><br />
    <%= f.text_field :data_fim %></div>

  <div><%= f.label :descricao %><br />
    <%= f.text_area :descricao %></div>

  <div><%= f.submit t("evento.new") %></div>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dionisio</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="content">
      <div class="header">
        <h1>Rio Curtição</h1>
        <%=  gravatar_image_tag(current_user.email, :alt => current_user.nome, :gravatar => {:size =>100}) if user_signed_in? %>
        <span  class="notice">
          <%= notice if notice %> </span>
        <span  class="alert">
          <%=  alert if alert %> </span>
        <% if !user_signed_in?  %>
          <%= link_to t("devise.sign_up"),new_user_registration_path  %>
          <%= link_to t("devise.sign_in"), new_user_session_path  %>
        <%else%>
          <%= link_to t("devise.sign_out"),logout_path  %>
        <%end%>
      </div>
      <div class="main">
        <%= yield %>
      </div>
      <div class="footer">
        2011
      </div>
    </div>


  </body>
</html>